config/routes.rb
Kodhjalpen::Application.routes.draw do
  devise_for :user_auths, path: "auth", path_names: 
    { sign_in: 'sign_in',
      sign_out: 'logout',
      password: 'secret',
      confirmation: 'verification',
      unlock: 'unblock',
      registration: 'register' }

  resources :developers, :only => [:new, :create, :edit, :show, :index, :update]
  resources :charities, :only => [:new, :create, :edit, :show, :index, :update]

  root :to => "cms_content#render_html"

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  has_one :user_auth, as: :authable
  accepts_nested_attributes_for :user_auth

  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :city, :mission, :name, :needs_help_with, :user_auth_attributes

  validates_presence_of :city, :name, :needs_help_with, :mission
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :occupation, :city, :user_auth_attributes

  has_one :user_auth, as: :authable

  accepts_nested_attributes_for :user_auth

  validates_presence_of :city, :first_name, :last_name

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :password, :password_confirmation

  validates :email, presence: true

  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

end

app/models/user_auth.rb
class UserAuth < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :authable, polymorphic: true, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :password, :password_confirmation

  validates :email, presence: true

  validates_format_of :email, :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/

  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :edit_user_path
  def current_user
    if user_auth_signed_in?
      return current_user_auth.authable
    end
  end
end

app/controllers/charities_controller.rb
# encoding: utf-8
class CharitiesController < ApplicationController
  def new
    @charity = Charity.new
    @charity.build_user_auth
  end

  def create
    @charity = Charity.new params[:charity]
    if @charity.save
      sign_in @charity.user_auth
      redirect_to root_path, notice: "Du har registrerats"
    else
      render :new
    end
  end

  def edit
    #OPTIMIZE Refactor to obilivion
    if current_user
      if current_user_auth.authable.class == Charity
        if current_user_auth.authable.id.to_s == params[:id]
          @charity = Charity.find params[:id]
        else
          flash[:error] = "Logga in för att uppdatera din profil"
          redirect_to root_url 
        end
      else
        flash[:error] = "Försökte redigera en ogiltig profil"
        redirect_to root_url 
      end
    else
      redirect_to root_url, notice: "Logga in för att uppdatera din profil"
    end
  end

  def index
    @charities = Charity.all
  end

  def update
    @charity = Charity.find(params[:id])
    if @charity.update_attributes(params[:charity])
      sign_in @charity.user_auth
      redirect_to root_path, :notice  => "Uppdaterat profil"
    else
      render :action => 'edit'
    end
  end
end

app/controllers/developers_controller.rb
# encoding: utf-8
class DevelopersController < ApplicationController
  def new
    @developer = Developer.new
    @developer.build_user_auth
  end

  def create
    @developer = Developer.new params[:developer]
    if @developer.save
      sign_in @developer.user_auth
      redirect_to root_path, notice: "Du har registrerats"
    else
      render :new
    end
  end

  def edit
    #OPTIMIZE Refactor to obilivion
    if current_user
      if current_user_auth.authable.class == Developer
        if current_user_auth.authable.id.to_s == params[:id]
          @developer = Developer.find params[:id]
        else
          flash[:error] = "Logga in för att uppdatera din profil"
          redirect_to root_url 
        end
      else
        flash[:error] = "Försökte redigera en ogiltig profil"
        redirect_to root_url 

      end
    else
      redirect_to root_url, notice: "Logga in för att uppdatera din profil"
    end
  end

  def index
    @developers = Developer.all
  end

  def update
    @developer = Developer.find(params[:id])
    if @developer.update_attributes(params[:developer])
      sign_in @developer.user_auth
      redirect_to root_path, :notice  => "Uppdaterat profil"
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cms_helper.rb
module CmsHelper
  def get_navigation
    #Pray to god that we only have one site
    @cms_site ||= Cms::Site.first

    @cms_site.pages.root.children.published.map do |page|
      get_navigation_link page.full_path, page.label
    end
  end

  def get_navigation_link path, link_name
    css_class = current_page?(path) ? "active" : ""
    link = link_to link_name, path 
    content_tag 'li', link, class: css_class
  end
end

app/helpers/developer_helper.rb
module DeveloperHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for model, field
    if model.errors[field].present?
      content_tag :span, :class => 'error_explanation' do
        model.errors[field].join(", ")
      end
    end
  end
end

app/views/charities/_form.html.erb
<%= simple_form_for @charity do |f| %>
  <%= f.error_notification %>
  
  <div class="inputs">
    <%= f.input :name, required: true, autofocus: true, label: "Vad heter ni?"  %>
    <%= f.input :mission, required: true, label: "Vad gör ni?" %>
    <%= f.input :needs_help_with, :required => true, label: "Vad skulle ni vilja ha hjälp med?" %>
    <%= f.input :city, :required => true, label: "Stad" %>
    <%= f.simple_fields_for :user_auth do |p| %>
      <%= p.input :email, required: true %>
      <%= p.input :password, required: true %>
      <%= p.input :password_confirmation, :required => true %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.button :submit, "Utför" %>
  </div>
<% end %>

app/views/charities/edit.html.erb
# encoding: utf-8
<h2>Registrering</h2>

<%= render :partial => 'form' %>

app/views/charities/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Namn</th>
      <th>Stad</th>
      <th>Målsättning</th>
      <th>Behöver hjälp med</th>
    </tr>
  </thead>
  <tbody>
    <% @charities.each do |charity| %>
      <tr>
        <td><%= charity.name %></td>
        <td><%= charity.city %></td>
        <td><%= charity.mission %></td>
        <td><%= charity.needs_help_with %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/charities/new.html.erb
# encoding: utf-8
<h2>Registrering</h2>

<%= render :partial => 'form' %>

app/views/developers/_form.html.erb
<%= simple_form_for @developer do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :first_name, :required => true, autofocus: true %>
    <%= f.input :last_name, :required => true %>
    <%= f.input :occupation, :required => true %>
    <%= f.input :city, :required => true %>
    <%= f.simple_fields_for :user_auth do |p| %>
      <%= p.input :email, required: true %>
      <%= p.input :password, required: true %>
      <%= p.input :password_confirmation, :required => true %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.button :submit, "Utför" %>
  </div>
<% end %>

app/views/developers/index.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Namn</th>
      <th>Stad</th>
      <th>Sysselsättnig</th>
    </tr>
  </thead>
  <tbody>
    <% @developers.each do |developer| %>
      <tr>
        <td><%= developer.full_name %></td>
        <td><%= developer.city %></td>
        <td><%= developer.occupation %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/developers/new.html.erb
# encoding: utf-8
<h2>Registrering</h2>

<%= simple_form_for @developer do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :first_name, :required => true, autofocus: true %>
    <%= f.input :last_name, :required => true %>
    <%= f.input :occupation, :required => true %>
    <%= f.input :city, :required => true %>
    <%= f.simple_fields_for :user_auth do |p| %>
      <%= p.input :email, :required => true, autofocus: true %>
      <%= p.input :password, :required => true %>
      <%= p.input :password_confirmation, :required => true %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.button :submit, "Börja göra nytta" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="se">
  <head>
    <title>Kodhjälpen</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
    </div>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Kodhjälpen</a>
          <%= render 'shared/navigation' %>
        </div>
      </div>
    </div>

    <div class="container">
      <%= render :partial => 'shared/flashes' %> 
      <%= yield %>

      <footer>
      <%= cms_snippet_content('footer') %>
    </div>
  </body>
</html>

app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Kodhjalpen" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Kodhjalpen</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_flashes.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert alert-success">
    <%= content_tag :div, flash[:notice] %>
  </div>
<% end %>

<% unless flash[:error].blank? %>
  <div class="alert alert-error">
    <%= content_tag :div, flash[:error] %>
  </div>
<% end %>

<% unless flash[:alert].blank? %>
  <div class="alert alert-block">
    <%= content_tag :div, flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<div class="nav-collapse">
  <ul class="nav">
    <%= get_navigation.inject('') { |result, el| result + el }.html_safe %>
  </ul>
  <ul class="nav pull-right">
    <%= get_navigation_link developers_path, "Utvecklare" %>
    <%= get_navigation_link charities_path, "Välgörenhet" %>
    <li class="divider-vertical"></li>

    <% if user_auth_signed_in? %>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <%= current_user_auth.email %> 
        <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <%= link_to "Uppdatera profil", edit_polymorphic_path(current_user) %>
        <%= link_to "Logga ut", destroy_user_auth_session_path, :method => :delete %>
      </ul>
      </li>
    <% else %>
      <%= content_tag :li, link_to("Logga in", new_user_auth_session_path) %>
      <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Registrera dig
        <b class="caret"></b></a>
      <ul class="dropdown-menu">
        <%= link_to("Utvecklare", new_developer_path) %>
        <%= link_to("Välgörenhet", new_charity_path) %>
      </ul>
      </li>
    <% end %>
  </ul>
</div><!--/.nav-collapse -->

app/views/user_auths/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Logga in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Registrera dig", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Glömt ditt lösenord?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Fick du inget bekräftelsemail?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Fick du inte upplåsningsinstruktioner?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Logga in med #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>